#define FORM_MAIN                                0
#define TEXTBOX_MAIN                             1
#define FORM_IFACE                               2
#define STRING_NONAME                            3
#define LIST_IFACE                               4
#define RUN_IFACE                                5
#define EDIT_IFACE                               6
#define NEW_IFACE                                7
#define FORM_EDIT                                8
#define FIELD_EDIT                               9
#define SCROLL_EDIT                              10
#define MENU_EDIT                                11
#define FORM_YESNO                               12
#define STRING_YESNO                             13
#define BUTTON_YESNOOK                           14
#define BUTTON_YESNOCANCEL                       15
#define FORM_NEW                                 16
#define TEXT_NEW                                 17
#define IFACE_MENU                               18
#define FORM_ABOUT                               19
#define LIST_ABOUT                               20
#define FORM_FONT                                21
#define STRING_NONAME3                           22
#define LIST_FONT                                23
#define OPEN_FONT                                24
#define DELETE_FONT                              25
