/* $Id: callbacks.h,v 1.6 2006-03-09 20:28:25 zeeb90au Exp $ */

/*
 * DO NOT EDIT THIS FILE - generated by Glade2Hildon version 1.0
 */
#include <gtk/gtk.h>

void on_break(GtkMenuItem* menuitem, gpointer user_data);
void on_reset_keys(GtkMenuItem* menuitem, gpointer user_data);
void on_about_activate(GtkMenuItem* menuitem, gpointer user_data);
void on_quit_activate(GtkMenuItem* menuitem, gpointer user_data);

/* End of $Id: callbacks.h,v 1.6 2006-03-09 20:28:25 zeeb90au Exp $ */
