/* $Id: interface.h,v 1.6 2006-06-27 12:27:49 zeeb90au Exp $ */

/*
 * DO NOT EDIT THIS FILE - generated by Glade2Hildon version 1.0
 */
#include <gtk/gtk.h>
#include <hildon-widgets/hildon-program.h>

GtkWidget* create_main_window();
GtkWidget* create_aboutdialog(void);
GtkWidget* create_opendialog(HildonProgram *app);

/* End of $Id: interface.h,v 1.6 2006-06-27 12:27:49 zeeb90au Exp $ */
