/* $Id: interface.h,v 1.7 2006-06-28 13:06:46 zeeb90au Exp $ */

/*
 * DO NOT EDIT THIS FILE - generated by Glade2Hildon version 1.0
 */
#include <gtk/gtk.h>
#include <hildon-widgets/hildon-program.h>

GtkWidget* create_main_window();
GtkWidget* create_aboutdialog(void);
GtkWidget* create_opendialog(GtkWindow *main_window);

/* End of $Id: interface.h,v 1.7 2006-06-28 13:06:46 zeeb90au Exp $ */
