/* $Id: interface.h,v 1.8 2006-07-22 13:16:08 zeeb90au Exp $ */

/*
 * DO NOT EDIT THIS FILE - generated by Glade2Hildon version 1.0
 */
#include <gtk/gtk.h>
#include <hildon-widgets/hildon-program.h>

GtkWidget* create_main_window();
GtkWidget* create_aboutdialog(void);
GtkWidget* create_opendialog(GtkWindow *main_window);
GtkWidget* create_savedialog(GtkWindow *main_window);

/* End of $Id: interface.h,v 1.8 2006-07-22 13:16:08 zeeb90au Exp $ */
