// This file is part of SmallBASIC
//
// Copyright(C) 2001-2012 Chris Warren-Smith.
//
// This program is distributed under the terms of the GPL v2.0 or later
// Download the GNU Public License (GPL) from www.gnu.org
//

/*
 * DO NOT EDIT THIS FILE - generated by Glade2Hildon version 1.0
 */
#include <gtk/gtk.h>

void on_break(GtkMenuItem *menuitem, gpointer user_data);
void on_reset_keys(GtkMenuItem *menuitem, gpointer user_data);
void on_save_screen(GtkMenuItem *menuitem, gpointer user_data);
void on_about_activate(GtkMenuItem *menuitem, gpointer user_data);
void on_quit_activate(GtkMenuItem *menuitem, gpointer user_data);

