// generated by Fast Light User Interface Designer (fluid) version 1.0100

#ifndef fb2p_h
#define fb2p_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Input.H>
#include "fmcb.h"
extern Fl_Input *f_src;
extern Fl_Input *f_trg;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *f_dispcode;
#include <FL/Fl_Button.H>
#include <FL/Fl_File_Chooser.h>
extern Fl_Text_Display *f_console;
Fl_Window* make_window();
#endif
