/* automagicaly generated file */
const char *code_keywords[] = { // List of basic level keywords
"APPEND", "AS", "BG", "BYREF", "CASE", "CHAIN", "CLOSE", "COLOR", 
"CONST", "DATA", "DECLARE", "DEF", "DELETE", "DIM", "ELIF", "ELSE", 
"ELSEIF", "END", "ENDIF", "ERASE", "EXEC", "EXIT", "EXPORT", "FI", 
"FOR", "FUNC", "GOSUB", "GOTO", "IF", "IMPORT", "INPUT", "INSERT", 
"LABEL", "LET", "LINE", "LINEINPUT", "LINPUT", "LOCAL", "LOGPRINT", "NEXT", 
"ON", "OPEN", "OPTION", "PRINT", "READ", "REDIM", "REM", "REPEAT", 
"RESTORE", "RETURN", "RUN", "SEEK", "SELECT", "SINPUT", "SPRINT", "STEP", 
"STOP", "SUB", "THEN", "TO", "TROFF", "TRON", "UNIT", "UNTIL", 
"USE", "USG", "USING", "WEND", "WHILE", "WRITE"};

const char *code_procedures[] = { // functions
"ARC", "AT", "BCOPY", "BEEP", "BLOAD", "BPUTC", "BSAVE", "BUTTON", 
"CALL", "CHART", "CHDIR", "CHMOD", "CIRCLE", "CLS", "COPY", "DATEDMY", 
"DELAY", "DERIV", "DIFFEQN", "DIRWALK", "DOFORM", "DRAW", "DRAWPOLY", "ENV", 
"ENVIRON", "EXPRSEQ", "HTML", "IMAGE", "IMGGET", "IMGPUT", "INTERSECT", "JOIN", 
"KILL", "LOCATE", "LOCK", "M3APPLY", "M3IDENT", "M3ROTATE", "M3SCALE", "M3TRANS", 
"MKDIR", "NOSOUND", "PAINT", "PAUSE", "PEN", "PLAY", "PLOT", "PLOT2", 
"POKE", "POKE16", "POKE32", "POLYEXT", "PSET", "RANDOMIZE", "RECT", "RENAME", 
"RMDIR", "ROOT", "RTE", "SEARCH", "SORT", "SOUND", "SPLIT", "STKDUMP", 
"SWAP", "TEXT", "TIMEHMS", "TLOAD", "TSAVE", "UNLOADLIB", "USRCALL", "VIEW", 
"WINDOW", "WSPLIT"};

const char *code_functions[] = { // functions
"ABS", "ABSMAX", "ABSMIN", "ACCESS", "ACOS", "ACOSH", "ACOT", "ACOTH", 
"ACSC", "ACSCH", "ARRAY", "ASC", "ASEC", "ASECH", "ASIN", "ASINH", 
"ATAN", "ATAN2", "ATANH", "ATN", "BALLOC", "BCS", "BGETC", "BIN", 
"CALL", "CAT", "CBS", "CDBL", "CEIL", "CHOP", "CHR", "CINT", 
"COS", "COSH", "COT", "COTH", "CREAL", "CSC", "CSCH", "DATE", 
"DATEFMT", "DEG", "DETERM", "DISCLOSE", "EMPTY", "ENCLOSE", "ENV", "ENVIRON", 
"EOF", "EXIST", "EXP", "FILES", "FIX", "FLOOR", "FORMAT", "FRAC", 
"FRE", "FREEFILE", "HEX", "IF", "IFF", "IMAGEH", "IMAGEW", "INKEY", 
"INPUT", "INSTR", "INT", "INVERSE", "ISARRAY", "ISDIR", "ISFILE", "ISLINK", 
"ISNUMBER", "ISSTRING", "JULIAN", "LBOUND", "LCASE", "LEFT", "LEFTOF", "LEFTOFLAST", 
"LEN", "LINEQN", "LOADLIB", "LOF", "LOG", "LOG10", "LOWER", "LTRIM", 
"MALLOC", "MAX", "MID", "MIN", "OCT", "PEEK", "PEEK16", "PEEK32", 
"PEN", "POINT", "POLYAREA", "POLYCENT", "POW", "PROGLINE", "PTDISTLN", "PTDISTSEG", 
"PTSIGN", "RAD", "REPLACE", "RGB", "RGBF", "RIGHT", "RIGHTOF", "RIGHTOFLAST", 
"RINSTR", "RND", "ROUND", "RTRIM", "RUN", "RUN", "SEC", "SECH", 
"SEEK", "SEGCOS", "SEGLEN", "SEGSIN", "SEQ", "SGN", "SIN", "SINH", 
"SPACE", "SPC", "SQR", "SQUEEZE", "STATMEAN", "STATMEANDEV", "STATSPREADP", "STATSPREADS", 
"STR", "STRING", "SUM", "SUMSQ", "TAB", "TAN", "TANH", "TEXTHEIGHT", 
"TEXTWIDTH", "TICKS", "TICKSPERSEC", "TIME", "TIMER", "TRANSLATE", "TRIM", "TXTH", 
"TXTW", "UBOUND", "UCASE", "UPPER", "VADR", "VAL", "WEEKDAY", "XPOS", 
"YPOS"};
