/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sourceforge_smallbasic_WebServer */

#ifndef _Included_net_sourceforge_smallbasic_WebServer
#define _Included_net_sourceforge_smallbasic_WebServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sourceforge_smallbasic_WebServer
 * Method:    execute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sourceforge_smallbasic_WebServer_execute
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
