.TH "pdb2bas" "1" "0.9.0" "Nicholas Christopoulos" "SmallBASIC Utilities"
.SH "NAME"
.LP 
pdb2bas \- Converts PalmOS files to text files
.SH "SYNTAX"
.LP 
pdb2bas <\fIfilename\fP>

.SH "DESCRIPTION"
.LP 
PalmOS files, created by SB for PalmOS, to simple text files (i.e. SmallBASIC source files)
.SH "EXAMPLES"
.LP 
To run this program type:
.LP 
pdb2bas myfile.pdb
.SH "AUTHORS"
.LP 
Nicholas Christopoulos <nereus@freemail.gr>
.SH "SEE ALSO"
.LP 
sbasic(1) pdb2bas(1) mkpdb(1)
