// generated by Fast Light User Interface Designer (fluid) version 1.0100

#include "fb2p.h"

Fl_Input *f_src=(Fl_Input *)0;

static void cb_f_src(Fl_Input* o, void*) {
  strcpy(srcfile, o->value());
src_update();
}

Fl_Input *f_trg=(Fl_Input *)0;

static void cb_f_trg(Fl_Input* o, void*) {
  strcpy(trgfile, o->value());
}

Fl_Text_Display *f_dispcode=(Fl_Text_Display *)0;

static void cb_(Fl_Button*, void*) {
  char *f;
f = fl_file_chooser("Source file",
	"SB PDB Files(*.pdb)\tSB Source Files (*.bas)\tAll Files (*)",
	srcfile);
if ( f )	{
	strcpy(srcfile, f);
	f_src->value(srcfile);
	src_update();
	};
}

static void cb_1(Fl_Button*, void*) {
  char *f;
f = fl_file_chooser("Target file","*",trgfile);
if ( f )	{
	strcpy(trgfile, f);
	f_trg->value(trgfile);
	};
}

static void cb_Convert(Fl_Button*, void*) {
  convert();
}

Fl_Text_Display *f_console=(Fl_Text_Display *)0;

Fl_Window* make_window() {
  Fl_Window* w;
  { Fl_Window* o = new Fl_Window(420, 392, "BAS2PDB");
    w = o;
    o->labelsize(12);
    { Fl_Input* o = f_src = new Fl_Input(70, 10, 305, 25, "Source file");
      o->box(FL_PLASTIC_DOWN_BOX);
      o->labelsize(12);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_f_src);
      o->align(68);
    }
    { Fl_Input* o = f_trg = new Fl_Input(70, 40, 305, 25, "Target file");
      o->box(FL_PLASTIC_DOWN_BOX);
      o->labelsize(12);
      o->textsize(12);
      o->callback((Fl_Callback*)cb_f_trg);
    }
    { Fl_Text_Display* o = f_dispcode = new Fl_Text_Display(10, 125, 400, 155, "Code preview");
      o->box(FL_PLASTIC_DOWN_FRAME);
      o->labelsize(12);
      o->textfont(4);
      o->textsize(12);
    }
    { Fl_Button* o = new Fl_Button(385, 10, 25, 25, "...");
      o->box(FL_DIAMOND_UP_BOX);
      o->down_box(FL_DIAMOND_UP_BOX);
      o->labelsize(12);
      o->callback((Fl_Callback*)cb_);
    }
    { Fl_Button* o = new Fl_Button(385, 40, 25, 25, "...");
      o->box(FL_DIAMOND_UP_BOX);
      o->labelsize(12);
      o->callback((Fl_Callback*)cb_1);
    }
    { Fl_Button* o = new Fl_Button(300, 80, 110, 25, "Convert");
      o->box(FL_ROUND_UP_BOX);
      o->labelsize(12);
      o->callback((Fl_Callback*)cb_Convert);
    }
    { Fl_Text_Display* o = f_console = new Fl_Text_Display(10, 305, 400, 75, "Console");
      o->box(FL_PLASTIC_DOWN_FRAME);
      o->labelsize(12);
      o->textsize(12);
    }
    o->end();
    o->resizable(o);
  }
  return w;
}
