/*
 * eBookman java-ish libraries
 * version 1.1
 *
 * Copyright(C) 2001 Chris Warren-Smith. Gawler, South Australia
 * cwarrens@twpo.com.au
 *
 *                  _.-_:\
 *                 /      \
 *                 \_.--*_/
 *                       v
 *
 * This program is distributed under the terms of the GPL v2.0 or later
 * Download the GNU Public License (GPL) from www.gnu.org
 * 
 */
#ifndef FORM_HH
#define FORM_HH

////////////////////////////////////////////////////////////////////////////////
// calls generated by rcp2ebm

struct Form : public CWindow {
    Form(U16 id);
    virtual ~Form();

    CMenuBar* getMenuBar() {return menuBar;}
    bool isModal() {return (this != GUI_TopWindow()); }

    S32 MsgHandler(MSG_TYPE type, CViewable *from, S32 data);

    private:
    CMenuBar *menuBar;
};

#endif
