.TH "bas2pdb" "1" "0.9.0" "Nicholas Christopoulos" "SmallBASIC Utilities"
.SH "NAME"
.LP 
bas2pdb \- Converts smallbasic source files to PalmOS file format
.SH "SYNTAX"
.LP 
bas2pdb <\fIfilename\fP>
.SH "DESCRIPTION"
.LP 
Converts smallbasic source files to pdb format (PalmOS DataBase)
.SH "EXAMPLES"
.LP 
To run this program type:
.LP 
bas2pdb myfile.sb
.SH "AUTHORS"
.LP 
Nicholas Christopoulos <nereus@freemail.gr>
.SH "SEE ALSO"
.LP 
sbasic(1) pdb2bas(1) mkpdb(1)
