.TH "mkpdb" "1" "0.9.0" "Nicholas Christopoulos" "SmallBASIC Utilities"
.SH "NAME"
.LP 
mkpdb \- Creates PalmOS files from binaries
.SH "SYNTAX"
.LP 
mkpdb \fI\-c CREA\fP \fI\-t TYPE\fP \fI\-o output.pdb\fP <\fIfiles\fP>
.SH "DESCRIPTION"
.LP 
This program packs files into a final PDB (PalmOS database file).
.SH "OPTIONS"
.LP 
.TP 
\fB\-c\fR <\fICREA\fP>
PDB\-Creator attribute.
.TP 
\fB\-t\fR <\fITYPE\fP>
PDB\-Type attribute.
.TP 
\fB\-o\fR <\fIoutput.pdb\fP>
The filename of the package.
.SH "EXAMPLES"
.LP 
To run this program type:
.LP 
mkpdb \-C SmBa \-T DATA \-o my.pdb file1 file2
.SH "AUTHORS"
.LP 
Nicholas Christopoulos <nereus@freemail.gr>
.SH "SEE ALSO"
.LP 
sbasic(1) bas2pdb(1) pdb2bas(1)
