char *help_page_d=
">> Graphics & Sound\n"
"_______________________________________________________________________\n"
"\n"
"The SB's Graphics commands are working only with integers.\n"
"(Of course, 2D algebra commands are working with reals)\n"
"That is different of QB, but its much faster.\n"
"\n"
"The colors\n"
"____________________________\n"
"\n"
"Color-mode              Colors\n"
"\n"
"Monochrome              0 = black, 15 = white\n"
"\n"
"2bit (4 colors)         0 = black, 15 = white,  \n"
"                        1-6,  8  = dark-gray,\n"
"                        7, 9-14 = light-gray\n"
"\n"
"4bit (16 colors)        16 Standard VGA colors\n"
"                        16 colors of gray (on PalmOS)\n"
"\n"
"8bit (256 paletted colors)\n"
"                        16 Standard VGA colors\n"
"                        The rest colors are ignored\n"
"\n"
"15bit (32K colors), 16bit (64K colors) and 24bit (1.7M colors)\n"
"\n"
"         color 0..15 is the standard VGA colors\n"
"         full 24-bit RGB colors can be passed by using negative number.\n"
"\n"
"\n"
"The points\n"
"____________________________\n"
"\n"
"Any point can be specified by an array of 2 elements or\n"
"by 2 parameters\n"
"\n"
"Example:\n"
"LINE x1, y1, x2, y2\n"
"or\n"
"LINE [x1, y1], [x2, y2]\n"
"\n"
"Also, the polylines can work with the same way.\n"
"DIM poly(10)\n"
"...\n"
"poly[0] = [x, y]\n"
"\n"
"\n"
"${key:step}\n"
"The STEP keyword\n"
"____________________________\n"
"\n"
"The STEP keyword calculates the next x,y parameters relative to current\n"
"position. That position can be returned by using the POINT(0) and \n"
"POINT(1) functions.\n"
"\n"
"\n"
"The 'aspect' parameter\n"
"____________________________\n"
"\n"
"The x/y factor.\n"
"\n"
"\n"
"${key:filled}\n"
"The FILLED keyword\n"
"____________________________\n"
"\n"
"The FILLED keyword fills the result of the command with the drawing\n"
"color.\n"
"\n"
"_______________________________________________________________________\n"
"\n"
"${key:arc}\n"
"ARC [STEP] x,y,r,astart,aend [,aspect [,color]] [COLOR color]\n"
"\n"
"Draws an arc\n"
"\n"
"astart,aend = first,last angle in radians.\n"
"_______________________________________________________________________\n"
"\n"
"${key:chart}\n"
"CHART {LINECHART|BARCHART}, array() [, {0|1|2|3} [, x1, y1, x2, y2]]\n"
"\n"
"Draws a chart of array values in the rectangular area x1,y1,x2,y2\n"
"\n"
"type:\n"
"0 = simple\n"
"1 = with marks\n"
"2 = with ruler\n"
"3 = with marks & ruler\n"
"_______________________________________________________________________\n"
"\n"
"${key:plot}\n"
"PLOT xmin, xmax USE f(x)\n"
"\n"
"Graph of f(x)\n"
"\n"
"Example:\n"
"PLOT 0, 2*PI USE SIN(x)\n"
"_______________________________________________________________________\n"
"\n"
"${key:circle}\n"
"CIRCLE [STEP] x,y,r [,aspect [, color]] [COLOR color] [FILLED]\n"
"\n"
"x,y - the circle's center\n"
"\n"
"r   - the radius\n"
"\n"
"Draws a circle (or an ellipse if the aspect is specified).\n"
"_______________________________________________________________________\n"
"\n"
"${key:color}\n"
"COLOR foreground-color [, background-color]\n"
"\n"
"Specifies the foreground and background colors \n"
"_______________________________________________________________________\n"
"\n"
"${key:drawpoly}\n"
"DRAWPOLY array\n"
"    [,x-origin,y-origin [, scalef [, color]]] [COLOR color] [FILLED]\n"
"\n"
"Draws a polyline\n"
"\n"
"even elements for x (starting from 0), odd elements for y\n"
"_______________________________________________________________________\n"
"\n"
"${key:draw}\n"
"DRAW string\n"
"\n"
"Draws an object according to instructions specified as a string.\n"
"\n"
"string - A string expression containing commands in the BASIC graphics\n"
"definition language.\n"
"\n"
"Graphics Definition Language \n"
"\n"
"In the movement instructions below, n specifies a distance to move.\n"
"The number of pixels moved is equal to n multiplied by the current\n"
"scaling factor, which is set by the S command.\n"
"\n"
"  Un    Move up.\n"
"\n"
"  Dn    Move down.\n"
"\n"
"  Ln    Move left.\n"
"\n"
"  Rn    Move right.\n"
"\n"
"  En    Move diagonally up and right.\n"
"\n"
"  Fn    Move diagonally down and right.\n"
"\n"
"  Gn    Move diagonally down and left.\n"
"\n"
"  Hn    Move diagonally up and left.\n"
"\n"
"Mx,y    Move to coordinate x,y. If x is preceded by a + or -, the\n"
"        movement is relative to the last point referenced.\n"
"\n"
"   B    A prefix command. Next movement command moves but doesn't\n"
"        plot.\n"
"\n"
"   N    A prefix command. Next movement command moves, but returns\n"
"        immediately to previous point.\n"
"\n"
"Notes:\n"
"    * This command it is had not tested, please report any\n"
"      bug or incompatibility.\n"
"_______________________________________________________________________\n"
"\n"
"${key:line}\n"
"LINE [STEP] x,y [{,|STEP} x2,y2] [, color | COLOR color]\n"
"\n"
"Draws a line\n"
"_______________________________________________________________________\n"
"\n"
"${key:pset}\n"
"PSET [STEP] x,y [, color | COLOR color]\n"
"\n"
"Draw a pixel\n"
"_______________________________________________________________________\n"
"\n"
"${key:rect}\n"
"RECT [STEP] x,y [{,|STEP} x2,y2] [, color | COLOR color] [FILLED]\n"
"\n"
"Draws a rectangular parallelogram\n"
"_______________________________________________________________________\n"
"\n"
"${key:txtw}${key:txth}${key:textwidth}${key:textheight}\n"
"TXTW(s), TXTH(s)\n"
"or\n"
"TEXTWIDTH(s), TEXTHEIGHT(s)\n"
"\n"
"Returns the text width or height of string s in pixels\n"
"_______________________________________________________________________\n"
"\n"
"${key:xpos}${key:ypos}\n"
"XPOS\n"
"YPOS\n"
"\n"
"Returns the current position of the cursor in \"characters\".\n"
"_______________________________________________________________________\n"
"\n"
"${key:point}\n"
"POINT(x[,y])\n"
"\n"
"Returns the color of the pixel at x,y\n"
"\n"
"if y does not specified x contains the info-code\n"
"0 = returns the current X graphics position\n"
"1 = returns the current Y graphics position\n"
"_______________________________________________________________________\n"
"\n"
"${key:paint}\n"
"PAINT [STEP] x, y [,color [,border]]\n"
"\n"
"Fills an enclosed area on the graphics screen with a specific color.\n"
"\n"
"x,y     - Screen coordinate (column, row) within the area that is\n"
"          to be filled.\n"
"\n"
"color   - The fill-color\n"
"\n"
"border  - The boundary-color\n"
"\n"
"if the border-color is specified then the PAINT will fill all the\n"
"area which is specified by the border-color. \n"
"(fill-until, color!=point(x,y)\n"
"\n"
"if the border-color is NOT specified then the PAINT will fill all\n"
"the are with the same color as the pixel at x,y.\n"
"(fill-while, color=point(x,y))\n"
"_______________________________________________________________________\n"
"\n"
"${key:view}\n"
"VIEW [x1,y1,x2,y2 [,color [,border-color]]]\n"
"\n"
"Defines a viewport.\n"
"\n"
"x1,y1,x2,y2     - Corner coordinates of the viewport.\n"
"color           - If included, BASIC fills the viewport with the\n"
"                  specified color. \n"
"border-color    - If included, BASIC draws a border, in a specified\n"
"                  color, around the defined viewport.\n"
"\n"
"The viewport defined by VIEW is disabled by a VIEW command with no \n"
"parameters.\n"
"_______________________________________________________________________\n"
"\n"
"${key:window}\n"
"WINDOW [x1,y1,x2,y2]\n"
"\n"
"Specifies \"world\" coordinates for the screen.\n"
"\n"
"x1,y1,x2,y2    The corner coordinates of the world space.\n"
"\n"
"The WINDOW command allows you to redefine the corners of the display\n"
"screen as a pair of \"world\" coordinates.\n"
"\n"
"The world space defined by WINDOW is disabled by a WINDOW command with\n"
"no parameters.\n"
"_______________________________________________________________________\n"
"\n"
"${key:rgb}${key:rgbf}\n"
"RGB(r,g,b)\n"
"RGBF(r,g,b)\n"
"\n"
"The RGB functions returns the RGB color codes for the specified values\n"
"\n"
"The RGB() takes values 0..255 for each of the color.\n"
"The RGBF() takes values 0..1 for each of the color.\n"
"\n"
"The return value is a negative 24bit value to by used by drawing \n"
"functions.\n"
"_______________________________________________________________________\n"
"\n"
"${key:beep}\n"
"BEEP\n"
"\n"
"Generates a beep sound\n"
"_______________________________________________________________________\n"
"\n"
"${key:play}\n"
"PLAY string\n"
"\n"
"Play musical notes\n"
"\n"
"A-G[-|+|#][nnn][.]      \n"
"        Play note A..G\n"
"        +|# - sharp\n"
"        - - flat\n"
"        . - multiplier 1.5\n"
"\n"
"On      - Octave 0..6\n"
"        <  - Moves down one octave\n"
"        >  - Moves up one octave\n"
"\n"
"Nnn     - Play note 0..84 (0 = pause)\n"
"Pnnn    - Pause 1..64\n"
"Lnnn    - Length of note 1..64 (1/nnn)\n"
"Tnnn    - Tempo 32..255. Number of 1/4 notes per minute.\n"
"\n"
"MS      - Staccato (1/2)\n"
"MN      - Normal (3/4)\n"
"ML      - Legato\n"
"\n"
"Vnnn    - Volume 0..100\n"
"\n"
"MF      - Play on foreground\n"
"MB      - Play on background\n"
"\n"
"Q       - Clear sound queue\n"
"_______________________________________________________________________\n"
"\n"
"${key:sound}\n"
"SOUND freq, dur_ms [, vol] [BG]\n"
"\n"
"Plays a sound\n"
"\n"
"freq    - The frequency\n"
"\n"
"dur_ms  - The duration in milliseconds\n"
"\n"
"vol     - The volume in 1/100 units\n"
"\n"
"BG      - Play it in background\n"
"\n"
"_______________________________________________________________________\n"
"\n"
"${key:nosound}\n"
"NOSOUND\n"
"\n"
"Stops background sound.\n"
"Also, clears the sound queue.\n"
"_______________________________________________________________________\n"
"\n"
;