char *help_page_e=
">> Miscellaneous\n"
"_______________________________________________________________________\n"
"\n"
"${key:randomize}\n"
"RANDOMIZE [int]\n"
"\n"
"Seeds the random number generator\n"
"_______________________________________________________________________\n"
"\n"
"${key:rnd}\n"
"RND\n"
"\n"
"Returns a random number from the range 0 to 1\n"
"_______________________________________________________________________\n"
"\n"
"${key:lbound}${key:ubound}\n"
"LBOUND(array [, dim])\n"
"UBOUND(array [, dim])\n"
"\n"
"Returns the lower/upper bound of the 'array'\n"
"\n"
"The parameter 'dim' is the array dimension whose bound is returned\n"
"\n"
"Example:\n"
"DIM v1(-4 TO 7)\n"
"DIM v2(1 TO 2, 3 TO 4)\n"
"\n"
"PRINT LBOUND(v1)   : REM -4\n"
"PRINT UBOUND(v1)   : REM 7\n"
"\n"
"PRINT LBOUND(v2)   : REM 1\n"
"PRINT LBOUND(v2,2) : REM 3\n"
"_______________________________________________________________________\n"
"\n"
"${key:cint}${key:creal}${key:cdbl}\n"
"CINT(x) - convert x to 32b integer\n"
"\n"
"CREAL(x) or CDBL(x) - convert x to 64b real number\n"
"\n"
"Meaningless. Used for compatibility.\n"
"_______________________________________________________________________\n"
"\n"
"${key:pen}\n"
"PEN ON|OFF\n"
"\n"
"Enables/Disables the PEN/MOUSE mechanism.\n"
"_______________________________________________________________________\n"
"\n"
"${key:pen}\n"
"PEN(0..14)\n"
"\n"
"Returns the PEN/MOUSE data.\n"
"\n"
"Values:\n"
"0 - true (non zero) if there is a new pen or mouse event\n"
"1 - PEN: last pen-down x; \n"
"    MOUSE: last mouse button down x \n"
"2 - Same as 1 for y \n"
"3 - true if the PEN is down; \n"
"    MOUSE: mouse left-button is pressed\n"
"4 - PEN: last/current x, \n"
"    MOUSE: the current x position only if the left\n"
"      mouse button is pressed (like PEN is down)\n"
"5 - Same as PEN(4) for y \n"
"\n"
"Mouse specific (non PalmOS):\n"
"\n"
"10 - current mouse x pos.\n"
"11 - current mouse y pos.\n"
"12 - true if the left mouse button is pressed\n"
"13 - true if the right mouse button is pressed\n"
"14 - true if the middle mouse button is pressed\n"
"_______________________________________________________________________\n"
"\n"
"${key:pause}\n"
"PAUSE [secs]\n"
"\n"
"Pauses the execution for a specified length of time, or until user hit\n"
"the keyboard.\n"
"_______________________________________________________________________\n"
"\n"
"${key:swap}\n"
"SWAP a, b\n"
"\n"
"Exchanges the values of two variables. The parameters may be variables\n"
"of any type.\n"
"\n"
"_______________________________________________________________________\n"
"\n"
;